import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientTransition from "./client-transition";
import BackButtonWrapper from "@/components/auth/BackButtonWrapper/BackButtonWrapper";
import NextButtonWrapper from "@/components/auth/NextButtonWrapper/NextButtonWrapper";
import { RegistrationProvider } from "@/context/register/RegisterContext";
import { LoginProvider } from "@/context/login/LoginContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sahand App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoginProvider>
          <RegistrationProvider>
            <BackButtonWrapper />
            <ClientTransition>{children}</ClientTransition>
            <NextButtonWrapper />
          </RegistrationProvider>
        </LoginProvider>
      </body>
    </html>
  );
}
